### ISSUE TITLE
[Server] 패키지 설치/ 타입스크립트 환경 구축/ 명령어 설정

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#2]
**Assignee** : 작성자 본명

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 패키지 설치

### TODO
1. [x] 서버 구축에 필요한 패키지 설치
2. [x] tsconfig 설정 (./outdir - dist, ./rootdir - src)
3. [x] src폴더 만들고 app.ts 파일 만들기 
4. [x] dev 관련 명령어, 컴파일 명령어, pm2 명령어 설정
