### ISSUE TITLE
[Server] ec2로 1차 배포 테스트/ ec2 내에 mysql로 데이터베이스 관리하기

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#29]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: ec2로 1차 배포 테스트/ ec2 내에 mysql로 데이터베이스 관리하기

### TODO
1. [x] ec2로 1차 배포 테스트
2. [x] ec2 인스턴스 내에 mysql을 설치 후 db 마이그레이션
3. [x] 배포를 위한 수정
