### ISSUE TITLE
[Server] 기본적인 서버 구축 후 테스트

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#3]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 타입스크립트와 익스프레스를 이용한 서버를 구축

### TODO
1. [ ] 타입스크립트로 코드를 먼저 작성 후 테스트
2. [ ] 자바스크립트로 컴파일 후 2차 테스트
3. [ ] ec2 인스턴스로 기본적인 배포 테스트
