### ISSUE TITLE
[Server] 라우터 파일 생성후 미들웨어 설정

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#4]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 깃북 API문서를 참고해 라우터 생성 

### TODO
1. [x] 타입스크립트를 통한 라우터를 생성
2. [x] 테스트용 콜백함수를 작성하여 로컬에서 테스트
3. [x] 자바스크립트로 컴파일 후 2차 로컬 테스트
4. [x] ec2를 이용한 배포 테스트
5. [x] morgan 'dev'옵션 설정
