### ISSUE TITLE
[Server] 컨트롤러 디렉토리에 각 라우터에 따른 메소드 정의한 파일을 담을 디렉토리 생성/ cors 모듈 연결

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#5]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 컨트롤러 디렉토리에 각 라우터에 따른 메소드 정의한 파일을 담을 디렉토리 생성

### TODO
1. [x] controller 디렉토리 안에 main, user, feed 디렉토리 생성
2. [x] 각 디렉토리에서 index파일 를 이용해 메소드 한곳으로 모야 export하기
4. [x]  테스트용 메소드를 생성하여 타입스크립트 내에서 1차 로컬 테스트
5. [x] 컴파일 후 2차 로컬 테스트
6. [x] ec2로 배포 후 3차 테스트
7. [x] cors 모듈 연결
