### ISSUE TITLE
[Server] 아파트 기능 만들기

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#55]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 아파트 기능 만들기

### TODO
1. [x]  주차별 요일별 이중 배열 생성
2. [x] 쓴 글을 createdAt 으로 조회하여
3. [x] 주차를 구하는 메소드로 주차를 구하고
4. [x] 요일을 구하는 메소드로 요일을 구하여
5. [x] 해당 자리 배열에 숫자를 카운팅
