### ISSUE TITLE
[Server] 쿠키path 설정/ 로그아웃 시 쿠키 삭제/ env example 파일 수정

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#59]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `fix`
- Detail: 로그아웃 시 쿠키 삭제/ env example 파일 수정

### TODO
1. [x] 로그아웃 메소드에 res.clearcookie를 설정하여 쿠키 제거
2. [x] env 파일에 cookie domain 설정 환경변수 지정
3. [x] path /main으로 설정
