### ISSUE TITLE
[Server] /main 메소드 작성

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#6]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 회원가입, 로그인 시 이메일 인증/ 인증 성공시 토큰 발급/ OAuth 인증 방식/ 정보 해싱하기

### TODO
1. [x] nodemailer 패키지를 이용하여 이메일 인증 방식 구현 -> 회원가입, 로그인
2. [x] 인증 성공시 토큰 발급 -> jwt 방식
3. [ ] 각종 정보를 Crypto 모듈을 이용하여 해싱 // 해싱할 것이 없음 -> crypto 패키지 지울 것을 고려
4. [x] sequelize를 이용해 user 테이블 생성
4. [ ] OAuth 인증 방식을 통한 로그인 처리 -> 인증시 오는 응답의 고유 ID를 이용 -> 사용하는 oauth 형태를 먼저 배우고 적용
5. [x] 지속적인 db 그리고 문서 수정 -> db diagram 수정, gitbook 수정
5. [x] 타입스크립트 환경에서 포스트맨을 이용하여 1차 테스트
6. [x] 자바스크립트로 컴파일 후 2차 테스트
7. [x] ec2로 배포 후 3차 테스트
