### ISSUE TITLE
[Server] 뱃지 수정 기능

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#61]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 뱃지 수정 기능 추가

### TODO
1. [x] 뱃지를 눌렀을 때 뱃지 아이디를 받으며 받은 뱃지 아이디의 뱃지를 isUsed 상태로
2. [x] 유효성 검사로 내가 쓰는 뱃지가 아니라면 안되도록 만든다.
3. [x] 내가 쓰는 뱃지가 맞다면 기존에 쓰고있던 뱃지의 isUsed를 0으로 바꿔주고 새로 쓰는 뱃지를 1로 바꿔준다.
4. [x] 만약 지금 쓰고 있는 뱃지를 한번 더 누르면 그 뱃지를 0으로 수정 해주면서 아무 뱃지도 착용하지 않은 상태이다.
