### ISSUE TITLE
[Server] /user 메소드 작성

### ISSUE THREAD

**Issue by Sangrae-Cho** [codestates/nhb-server#8]
**Assignee** : 조상래

### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: user 개인적인 활동에 관련된 메소드 작성

### TODO
1. [x] gitbook을 참고하여 작성
2. [x] user 개인정보 조회
3. [x] user 개인피드 조회
4. [x] user 개인정보 에디트
5. [ ] user 뱃지 에디트
6. [x] 지속적인 db, 문서 수정
7. [x] 타입스크립트 환경 1차 테스트
8. [x] 자바스크립트 컴파일 후 2차 테스트
9. [x] ec2 배포 후 3차 테스트
